[project]
name = "auto-aeac-2026-task-1-comp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black==24.2.0",
    "depthai>=3.3.0",
    "numpy>=2.4.2",
    "open3d>=0.19",
    "opencv-python>=4.13.0.92",
    "pymavlink>=2.4.49",
    "pyserial>=3.5",
    "pytest>=9.0.2",
    "rerun-sdk>=0.30.0",
    "scikit-learn>=1.4",
    "scipy>=1.17.1",
]

[build-system]
requires = ["uv_build>=0.10.6,<0.11.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["airside", "groundstation"]
